[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
padding = { x = 4, y = 5 }

[font]
normal = { family = "MonoLisa Nerd Font", style = "Regular" }
bold = { style = "ExtraBold" }
italic = { style = "Italic" }
bold_italic = { style = "ExtraBold Italic" }
builtin_box_drawing = false
size = 13
