# Use C-s as the prefix
unbind C-b
set -g prefix C-s
bind-key C-s send-prefix

# Use true colour
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Use 1 as first window/pane index
set -g base-index 1
set -g pane-base-index 1

# Using 'vi' explicitly, which causes `copy-mode-vi` keymap to be used
# If not set explicitly, tmux will try to implcitly guess it by regex'ing over
# the value of $EDITOR
set -g mode-keys vi

# Automatically renumber windows when closing
set -g renumber-windows on

# Allow mouse scrolling
set -g mouse on

# Use a 24-hour clock
set -g clock-mode-style 24

# Reduce the default delay when sending escape (increase vim responsiveness)
set -g escape-time 0

# Increase the default scrollback history
set -g history-limit 1000000

set -g focus-events on        # Required for client-focus-in/out hooks

# Escape sequences that control the terminal (e.g. setting the background
# colour) should not be intercepted by tmux
set -g allow-passthrough on

# Set the terminal title
set -g set-titles on
set -g set-titles-string '#{session_name} - #{window_index}:#{window_name}'

# Add some vim-style bindings
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind ^ last-window
bind - last-window
bind -T copy-mode-vi v send-keys -X begin-selection

# Reload config and refresh all sessions
bind -N "Reload config" C-r run-shell 'tmux source-file ~/.config/tmux/tmux.conf && tmux list-sessions -F "#S" | while read -r s; do tmux set -t "$s" -u status; done | tmux display-message "Reloaded config"'

# Run tmux-sesh in a pop-up from anywhere with ctrl+g
bind -N "Create or swap to a session in a different directory" -n C-g display-popup -E ,tmux-sesh

# Status bar styling
set -g status on

# Refresh the status bar every 5 seconds (needed to show accurate clock)
set -g status-interval 5

# Make colours less garish
colour_base="default"
colour_grey="white"
colour_blue="blue"
colour_cyan="cyan"

set -g status-style "bg=$colour_base,fg=$colour_blue"
set -g window-status-current-style "bg=$colour_base,fg=$colour_cyan"
set -g status-right-style "bg=$colour_base,fg=$colour_blue"

# Make sure the right-most part of the session name is visible if it's too long
set -g status-left "[#{=-20:session_name}] "
set -g status-left-length 23

# %V  ISO week number (01-53)
# %j  day of year (001-366)
# %F  ISO date (YYYY-MM-DD)
# See `man strftime` for more
day_week="#[fg=$colour_grey]w%V d%j"
date="#[fg=default]%F"
time="#[fg=$colour_cyan]%H:%M"
set -g status-right "$day_week $date $time"

# Dim status bar when terminal loses focus
set-hook -g client-focus-in  "set -g status-style 'fg=$colour_blue' ; set -g status-right-style 'fg=$colour_blue' ; set -g window-status-current-style 'fg=$colour_cyan' ; set -g status-right '$day_week $date $time'"
set-hook -g client-focus-out "set -g status-style 'fg=$colour_grey' ; set -g status-right-style 'fg=$colour_grey' ; set -g window-status-current-style 'fg=$colour_grey' ; set -g status-right '$date'"
